#!/usr/bin/env bash
# living-docs / Stop hook — auto-maintains a project changelog (notes file).
#
# Deterministic, no LLM, no network. On every stop it regenerates a single
# idempotent AUTO-DRAFT block in the notes file, listing the uncommitted files
# that match the configured content pattern plus any IDs found in them. The
# block is replaced (never duplicated) on each run and disappears once the work
# is committed. Enrich it (context, status) and delete the markers before
# committing the real entry.
#
# This plugin ships with NO project-specific defaults: without a content
# pattern it does nothing. Configure per-repo via .claude/livingdocs.json:
#   { "notesFile": "CHANGELOG.md",                 // optional; auto-detects conversation_notes.md / CHANGELOG.md
#     "contentPattern": "<grep -E regex vs paths>",// REQUIRED for auto-drafting
#     "imageIdPattern": "<grep -E regex>" }         // optional; trailing digits are extracted as IDs
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
cd "$root" 2>/dev/null || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

notes_rel=""
pattern=""
idpat=""
cfg="$root/.claude/livingdocs.json"
if [ -f "$cfg" ] && command -v jq >/dev/null 2>&1; then
  notes_rel="$(jq -r '.notesFile // empty'      "$cfg" 2>/dev/null)"
  pattern="$(jq -r '.contentPattern // empty'   "$cfg" 2>/dev/null)"
  idpat="$(jq -r '.imageIdPattern // empty'     "$cfg" 2>/dev/null)"
fi

# Without a content pattern the plugin cannot know what "content" means -> no-op.
[ -z "$pattern" ] && exit 0

# Resolve the notes file (config wins; else auto-detect a common one).
if [ -z "$notes_rel" ]; then
  for cand in conversation_notes.md CHANGELOG.md NOTES.md; do
    [ -f "$root/$cand" ] && { notes_rel="$cand"; break; }
  done
fi
[ -z "$notes_rel" ] && exit 0   # nowhere sensible to write
notes="$root/$notes_rel"

mapfile -t files < <(
  { git diff --name-only HEAD 2>/dev/null; git ls-files --others --exclude-standard 2>/dev/null; } \
    | grep -E "$pattern" | sort -u
)
[ "${#files[@]}" -eq 0 ] && exit 0

draft="$(mktemp)"
{
  echo '<!-- AUTO-DRAFT:START — regenerated by the living-docs plugin. Enrich (context, status), then delete these markers before committing. -->'
  echo "## Session draft: $(date +%F) — auto-generated inventory (needs detail + status)"
  echo ""
  echo "Uncommitted files in the working tree:"
  for f in "${files[@]}"; do
    if [ -f "$f" ]; then
      ids=""
      [ -n "$idpat" ] && ids="$(grep -oE "$idpat" "$f" 2>/dev/null | grep -oE '[0-9]+' | sort -un | paste -sd, - | sed 's/,/, /g' || true)"
      [ -n "$ids" ] && echo "- \`$f\` (ids: $ids)" || echo "- \`$f\`"
    else
      echo "- \`$f\` (deleted)"
    fi
  done
  echo ""
  echo "_TODO before commit: add the context/sources and status, then remove the AUTO-DRAFT markers above and below._"
  echo '<!-- AUTO-DRAFT:END -->'
} > "$draft"

[ -f "$notes" ] || : > "$notes"

tmp="$(mktemp)"
awk -v draftfile="$draft" '
  function emit_draft(   line) {
    while ((getline line < draftfile) > 0) print line
    close(draftfile)
  }
  BEGIN { skip = 0; inserted = 0 }
  /<!-- AUTO-DRAFT:START/ { skip = 1; next }
  /<!-- AUTO-DRAFT:END/   { skip = 0; next }
  skip == 1 { next }
  {
    print
    if (!inserted && $0 == "---") { print ""; emit_draft(); print ""; inserted = 1 }
  }
  END { if (!inserted) emit_draft() }
' "$notes" > "$tmp" && mv "$tmp" "$notes"
rm -f "$draft"

echo "living-docs: refreshed AUTO-DRAFT inventory in $notes_rel (${#files[@]} file(s)). Add context/status and delete the AUTO-DRAFT markers before committing." >&2
exit 0
