#!/usr/bin/env bash
# living-docs / Stop hook (1/2) — auto-maintains an inventory of uncommitted work.
#
# Writes a single idempotent draft file listing uncommitted files (filtered by
# the configured content pattern). Regenerated on every stop; disappears once
# work is committed.
#
# Output destination (in priority order):
#   1. `.agent-memory/inventory/AUTO-DRAFT.md` — if `.agent-memory/` exists
#      (the cross-agent, markdown-first convention this plugin ships with as
#      of v0.3.0)
#   2. The legacy notes file at the project root (CHANGELOG.md /
#      conversation_notes.md / NOTES.md / config-supplied `notesFile`) — for
#      backward compat with v0.2.0 installs
#
# Deterministic. No LLM. No network. No `jq` required for the modern path
# (only used to read optional config).
#
# Configure per-repo via .claude/livingdocs.json (all optional):
#   { "notesFile": "CHANGELOG.md",                // legacy path only
#     "contentPattern": "<grep -E regex vs paths>", // filter; default: all changes
#     "imageIdPattern": "<grep -E regex>" }       // optional ID extractor
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
cd "$root" 2>/dev/null || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

# --- Load config (optional) -------------------------------------------------
notes_rel=""
pattern=""
idpat=""
cfg="$root/.claude/livingdocs.json"
if [ -f "$cfg" ] && command -v jq >/dev/null 2>&1; then
  notes_rel="$(jq -r '.notesFile // empty'    "$cfg" 2>/dev/null)"
  pattern="$(jq -r '.contentPattern // empty' "$cfg" 2>/dev/null)"
  idpat="$(jq -r '.imageIdPattern // empty'   "$cfg" 2>/dev/null)"
fi

# --- Collect uncommitted files ---------------------------------------------
# If no contentPattern is configured, match everything (the modern default).
# The legacy v0.2.0 plugin was a no-op without a pattern; we relax that here
# so the inventory works out-of-the-box when `.agent-memory/` is present.
files_raw="$(
  { git diff --name-only HEAD 2>/dev/null; git ls-files --others --exclude-standard 2>/dev/null; } \
    | sort -u
)"
if [ -n "$pattern" ]; then
  files_raw="$(printf '%s\n' "$files_raw" | grep -E "$pattern" || true)"
fi
mapfile -t files < <(printf '%s\n' "$files_raw" | sed '/^$/d')
[ "${#files[@]}" -eq 0 ] && exit 0

# --- Build the inventory block ---------------------------------------------
build_block() {
  echo '<!-- AUTO-DRAFT — regenerated by the living-docs plugin on every Stop. Safe to ignore in code review; do NOT commit this file with substantive narrative — promote enriched content to .agent-memory/sessions/ or decisions/. -->'
  echo "# Inventory — uncommitted work as of $(date '+%Y-%m-%d %H:%M')"
  echo ""
  echo "Branch: \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)\`"
  echo ""
  echo "## Uncommitted files (${#files[@]})"
  echo ""
  for f in "${files[@]}"; do
    if [ -f "$f" ]; then
      ids=""
      [ -n "$idpat" ] && ids="$(grep -oE "$idpat" "$f" 2>/dev/null | grep -oE '[0-9]+' | sort -un | paste -sd, - | sed 's/,/, /g' || true)"
      [ -n "$ids" ] && echo "- \`$f\` (ids: $ids)" || echo "- \`$f\`"
    else
      echo "- \`$f\` (deleted)"
    fi
  done
}

# --- Modern path: .agent-memory/inventory/AUTO-DRAFT.md --------------------
if [ -d "$root/.agent-memory" ]; then
  mkdir -p "$root/.agent-memory/inventory"
  build_block > "$root/.agent-memory/inventory/AUTO-DRAFT.md"
  echo "living-docs: refreshed .agent-memory/inventory/AUTO-DRAFT.md (${#files[@]} file(s))." >&2
  exit 0
fi

# --- Legacy path: edit a project-root notes file ---------------------------
if [ -z "$notes_rel" ]; then
  for cand in conversation_notes.md CHANGELOG.md NOTES.md; do
    [ -f "$root/$cand" ] && { notes_rel="$cand"; break; }
  done
fi
[ -z "$notes_rel" ] && exit 0
notes="$root/$notes_rel"

draft="$(mktemp)"
{
  echo '<!-- AUTO-DRAFT:START — regenerated by the living-docs plugin. Enrich (context, status), then delete these markers before committing. -->'
  echo "## Session draft: $(date +%F) — auto-generated inventory (needs detail + status)"
  echo ""
  echo "Uncommitted files in the working tree:"
  for f in "${files[@]}"; do
    if [ -f "$f" ]; then
      ids=""
      [ -n "$idpat" ] && ids="$(grep -oE "$idpat" "$f" 2>/dev/null | grep -oE '[0-9]+' | sort -un | paste -sd, - | sed 's/,/, /g' || true)"
      [ -n "$ids" ] && echo "- \`$f\` (ids: $ids)" || echo "- \`$f\`"
    else
      echo "- \`$f\` (deleted)"
    fi
  done
  echo ""
  echo "_TODO before commit: add the context/sources and status, then remove the AUTO-DRAFT markers above and below._"
  echo '<!-- AUTO-DRAFT:END -->'
} > "$draft"

[ -f "$notes" ] || : > "$notes"

tmp="$(mktemp)"
awk -v draftfile="$draft" '
  function emit_draft(   line) {
    while ((getline line < draftfile) > 0) print line
    close(draftfile)
  }
  BEGIN { skip = 0; inserted = 0 }
  /<!-- AUTO-DRAFT:START/ { skip = 1; next }
  /<!-- AUTO-DRAFT:END/   { skip = 0; next }
  skip == 1 { next }
  {
    print
    if (!inserted && $0 == "---") { print ""; emit_draft(); print ""; inserted = 1 }
  }
  END { if (!inserted) emit_draft() }
' "$notes" > "$tmp" && mv "$tmp" "$notes"
rm -f "$draft"

echo "living-docs (legacy): refreshed AUTO-DRAFT inventory in $notes_rel (${#files[@]} file(s)). Add context/status and delete the AUTO-DRAFT markers before committing." >&2
exit 0
