#!/usr/bin/env bash
# living-docs / Stop hook (2/2) — maintains a per-day session narrative.
#
# On every Stop, regenerate (idempotently) `.agent-memory/sessions/YYYY-MM-DD.md`
# with a deterministic, git-derived skeleton:
#   - branch
#   - commits authored today on this branch
#   - files changed today (committed + uncommitted)
#   - placeholder "What we did" / "Why it matters" sections for the human
#     (or a later LLM pass) to fill in
#
# Deterministic. No LLM. No network. The narrative is the *user's* contribution;
# the plugin only provides the scaffolding so the file exists, is dated, and
# already lists what's mechanically known about the day's work.
#
# No-op if `.agent-memory/` doesn't exist (i.e. project hasn't adopted the
# v0.3.0 convention yet).
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
cd "$root" 2>/dev/null || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0
[ -d "$root/.agent-memory" ] || exit 0

today="$(date +%F)"
sess_dir="$root/.agent-memory/sessions"
sess_file="$sess_dir/$today.md"
mkdir -p "$sess_dir"

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

# Commits authored today on the current branch
commits="$(git log --since="$today 00:00:00" --until="$today 23:59:59" \
  --pretty=format:'%h %s' 2>/dev/null || true)"

# Files touched today: committed (since midnight) ∪ uncommitted
mapfile -t committed_today < <(
  git log --since="$today 00:00:00" --until="$today 23:59:59" \
    --name-only --pretty=format: 2>/dev/null \
    | sed '/^$/d' | sort -u
)
mapfile -t uncommitted < <(
  { git diff --name-only HEAD 2>/dev/null; git ls-files --others --exclude-standard 2>/dev/null; } \
    | sort -u | sed '/^$/d'
)

# Build the deterministic block (replaces existing AUTO-DERIVED block if present;
# preserves any human-written content above/below the markers).
block="$(mktemp)"
{
  echo "<!-- AUTO-DERIVED:START — regenerated by living-docs at session end. Edit OUTSIDE these markers; everything inside is overwritten on the next stop. -->"
  echo "## Mechanically derived (auto-generated $(date '+%H:%M'))"
  echo ""
  echo "- **Branch:** \`$branch\`"
  if [ -n "$commits" ]; then
    echo "- **Commits today on this branch:**"
    printf '%s\n' "$commits" | sed 's/^/    - /'
  else
    echo "- **Commits today on this branch:** _(none)_"
  fi
  if [ "${#committed_today[@]}" -gt 0 ]; then
    echo "- **Files committed today (${#committed_today[@]}):**"
    printf '%s\n' "${committed_today[@]}" | sed 's/^/    - `/' | sed 's/$/`/'
  fi
  if [ "${#uncommitted[@]}" -gt 0 ]; then
    echo "- **Uncommitted in working tree (${#uncommitted[@]}):**"
    printf '%s\n' "${uncommitted[@]}" | sed 's/^/    - `/' | sed 's/$/`/'
  fi
  echo "<!-- AUTO-DERIVED:END -->"
} > "$block"

# If the session file doesn't exist, create it with full scaffolding,
# including the LLM-NARRATIVE markers used by the opt-in `consolidate.sh`.
if [ ! -f "$sess_file" ]; then
  {
    echo "# $today — session log"
    echo ""
    echo "<!-- LLM-NARRATIVE:START — \`consolidate.sh\` rewrites between these markers. Edit OUTSIDE to keep your changes. Until you run consolidate (or write manually), this block stays as a placeholder. -->"
    echo "### What we did"
    echo ""
    echo "_(fill in manually, or run \`bash \$CLAUDE_PLUGIN_ROOT/scripts/consolidate.sh\` to derive this from today's git context with your existing LLM)_"
    echo ""
    echo "### Why it matters"
    echo ""
    echo "_(fill in manually, or via consolidate)_"
    echo "<!-- LLM-NARRATIVE:END -->"
    echo ""
    cat "$block"
  } > "$sess_file"
  echo "living-docs: created .agent-memory/sessions/$today.md (fill in narrative; mechanical block auto-refreshes)." >&2
else
  # Replace the AUTO-DERIVED block in place; leave the rest untouched.
  tmp="$(mktemp)"
  awk -v blkfile="$block" '
    function emit_block(   line) {
      while ((getline line < blkfile) > 0) print line
      close(blkfile)
    }
    BEGIN { skip = 0; replaced = 0 }
    /<!-- AUTO-DERIVED:START/ { skip = 1; emit_block(); replaced = 1; next }
    /<!-- AUTO-DERIVED:END/   { skip = 0; next }
    skip == 1 { next }
    { print }
    END { if (!replaced) { print ""; emit_block() } }
  ' "$sess_file" > "$tmp" && mv "$tmp" "$sess_file"
  echo "living-docs: refreshed AUTO-DERIVED block in .agent-memory/sessions/$today.md." >&2
fi

rm -f "$block"
exit 0
